---
- name: Create dynamic inventory file
  hosts: localhost
  tasks:
  - name: Get Public IP of EC2 instance
    shell: terraform output raddit_public_ip
    args: 
     chdir: ../terraform
    register: raddit_public_ip 
  - debug:
     var: raddit_public_ip.stdout  

  - name: Create host file from template
    template:
     src: hosts.j2
     dest: hosts.yml
    vars:
     raddit_ipaddress: "{{ raddit_public_ip.stdout }}"
